language: node_js
node_js:
  - '11'
  - '10'
install:
  - yarn install
script:
  - yarn run lint
  - yarn run build --prod
before_deploy:
  - cd dist/form-elements
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: PZ7AQtol8ty7BjtgG3IhZ26cCcLoZK9tpRrofy6mWupdn3KO+88LCNAf/VYF2XVvAmpMXUb8EbjkLh1qrpumXAv/2COZ0Yi8VofgzAEKpu+Mxm7ixBYvaDR8ohEVEIvq6a9MfbqMXs2Gvx+/BX+OZ6Kwk/OTQi03qIMEdqVMB63++fae6G/eS3PjzLhhxt2oETTQBB7xeWx/1DlsnGWkehLytbBnED1kcSgBE/TZRYrRebFJihX2GDVMejGJHgiT2s6sq3YAkERDJf/LzV5c2qBsFbHn+akgycCQOKwRmWA7qGpvLEZTLlBCylS22mMh6QZXw0ZmpfCeHGui8fBxga3W7v6UwURzT4YCx5t6ebP8Zp1ANUgrt6iQvuyQpkyKkGWjBIQnFoGITPg8lKGRQjCsFQXlcvLKXJv9+q+2scTEmJJSNKyEb2vAfrMVYz20F3hxWWn1fbxNKkGm/7uHC2tlZYlaUGaoFrz4RZp5KkMTgAzqxsIZLMlG0Vd55wopouE3IP+Jz6yC55yfLJCwvTknCodRRr5jHmkj+2I3txVoYdB0/gDASUilyzPNuPZgCTTnvAwcMwy5CbwdHebcyXj/LYmep7HlrFxDTy+YapGbD5PY8Vi1UwIHJ+5DnbtSbjUnU5NyaC2v+d6L1IyTtaPkW9awXRjSg7wPaS0UH/I=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 11
notifications:
  slack:
    rooms:
      - secure: m7EAgRrYaXbo5LDa0Mpi1cQslC0tcxZRc100EjAn+uIPruyABJASIxHUjZeGJQmk98uiS7xk8c+asWx0HgTsj1c8qPMc5rIpfREMGThHBZ3hXzS38DaqehYtwbHPmVSe4tcdt6kj031cHgEzLocMXst9Lj7QO7fKLP/CWT9ZTcL5m8tnIoWMn40r/azvWl0NiFLhZTWdnI9Rn2vyfMuc7EhaUK4gJNwKL8qvSRvdgXR5pq/ETKpXgLTzRwGx7i9fXszecdptx5cRpAGhiRwbqXw9yPYL958KSpRPv+1DE7hX5UbrkecmfYULMfehWtmljTbgfw8cHb1WmIcO1W5M1IEKlBycoX5fxXKUgfv1uG2wF4LYT0U17k6muD/iXDoitq6AgxlDUzVnGQ1n+BQqkdVC9Alsb9fIzzoHejBy7PEXnRbSftnFIBc7AOwmNoQdGaJrNBdSN02OXx3eFuEQpjehdL1l/GMfok9jFlzdK5SpU6k8TPHQBehQ816KFAR+8IEn0XMQsyVVSjMTzYwop/rJONt/Ebtj1ifV+kZb1+IcvAJZ1PTR5ckg4bqFR1Xwg0Ue8pGvlgFtxALf+6FnzrwSpNHBYA/uNFiOG63aI0hNcnbTp0Uan/RI4GdZTzBA37ceQJPozdJ9o1UT9o3HCptnRP0gbSiEC6GvUsWZ0Qg=
    on_success: change
    on_failure: always
