language: node_js
node_js:
  - '13'
  - '12'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run lint
  - yarn run build
before_deploy:
  - cd dist/form-elements
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: eKpeVyOftQIV1uECH6VANvf9/InAItUKJhThdxE5lSycNAcedTyoR0WfzQZXn6m+mPZKk3ujuRQMbEFgfRzt4oADx5Tp8cRUplHAKHh9wSt5Vyl1iKxH95urTExv6Qlof07VaJ/0oPGchVCNUr9nwJJTr7KoO6eFEtaF8ddSgIQmhhXWP4x68Eq2g78EWd/dnIHh4aXCj0NMPUL5CxQ3W+ttp4uqp4pHj7k/cgpnKuAcoYli97uItdfwXapGalYTYKC1Fdqq8T04vB3yaflSnxFQuEUWWdKaCXw0fe4akpKDEeJb9U/it4ArwgzRWWnvUoIsK6AK8CpNybeac4zV8c8ydqymV3EbKbZr14OkpgO2Fn2N21FoTElClrJ7ZIiq5swdBNvq4BHKQCVqNGBgHUuqZ7wXA/xQNMhkVAJfHfAfoepxYCKac9KvmEnlCujlguHYBOM6gJkG3n2SnLtsp7EtL8QS9amNnwRSu9YDn6OMBWy6zr+tEqTX8h+2gvxK9BWFla/BdI28yBRtLQ1CsuurqKB8Xc0easSDb1EXCAVKzQHAeLVnPnAWr6Fq/H1Lgck0OfpCap2m4G5E0XGAXzmvD7YREW4crd8mCDIDrQ+IViLyWqRX1GIeW52y/blpwlewVI5c2V/W1Ptlg4EI2OOsuro4Af2WWtMTJ3md13c=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 13
notifications:
  slack:
    rooms:
      - secure: m7EAgRrYaXbo5LDa0Mpi1cQslC0tcxZRc100EjAn+uIPruyABJASIxHUjZeGJQmk98uiS7xk8c+asWx0HgTsj1c8qPMc5rIpfREMGThHBZ3hXzS38DaqehYtwbHPmVSe4tcdt6kj031cHgEzLocMXst9Lj7QO7fKLP/CWT9ZTcL5m8tnIoWMn40r/azvWl0NiFLhZTWdnI9Rn2vyfMuc7EhaUK4gJNwKL8qvSRvdgXR5pq/ETKpXgLTzRwGx7i9fXszecdptx5cRpAGhiRwbqXw9yPYL958KSpRPv+1DE7hX5UbrkecmfYULMfehWtmljTbgfw8cHb1WmIcO1W5M1IEKlBycoX5fxXKUgfv1uG2wF4LYT0U17k6muD/iXDoitq6AgxlDUzVnGQ1n+BQqkdVC9Alsb9fIzzoHejBy7PEXnRbSftnFIBc7AOwmNoQdGaJrNBdSN02OXx3eFuEQpjehdL1l/GMfok9jFlzdK5SpU6k8TPHQBehQ816KFAR+8IEn0XMQsyVVSjMTzYwop/rJONt/Ebtj1ifV+kZb1+IcvAJZ1PTR5ckg4bqFR1Xwg0Ue8pGvlgFtxALf+6FnzrwSpNHBYA/uNFiOG63aI0hNcnbTp0Uan/RI4GdZTzBA37ceQJPozdJ9o1UT9o3HCptnRP0gbSiEC6GvUsWZ0Qg=
    on_success: never
    on_failure: always
    on_pull_requests: false
