language: node_js
node_js:
  - '13'
  - '12'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run lint
  - yarn run build --prod
before_deploy:
  - cd dist/form-elements
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_token:
    secure: JG27nEuljHR8yY8KmU1ag93ucTVi//w8NVdgLKLtXlnyERs06ijfICvdI6aS9BzRxVoxfrlGeDUjApIQ5sYcY7u5/ZsGJvZENaBfQR3wOmebeUb/m9cAf8/m5hr0SsEiZYssRMJSnQbn2VeqV4G0aLEvKmonwqxzAWYCgLY+YCCgAi8H1/arGh/ZI4DPwgbvPqV+w+y2GIaZ8lyLz+Q0l8dqi7S0dDUX4L9Vjwgdlnb2bAZhxGRFTuWG2FToRa6zkfdQ7v+CWxWRsJ7vBQjWFwNGUMXkcqbAwlegygO7d6JJvGO799PKPzfIUb8jGsl4qb3SedIiVNyEcmL8neTkxIMosYjhEmh11y3TPmRxqRuaToT6wRDKVbRIQptej9vWKD09URz+FO+O6CegD+VKHGgK8++Vn8kLSHR9YdXhtPXwGQyvi1nMLrUJGjaUlaKqxu2HZo8nHvggo65M6Lo0vobodCd+XzSDnZWAKE9TvbAkfqMrEKd5lDGUuhJBkTWiffe8QNbF3LTL2Eh7WoIVf7sZShZAqSO4aXZlkkJyjG6ovQ4ICfu0G9s4yjGMusxN6m+PxUzvzxrf9DKAU6C+HRD8Mghwei6W51dE6mOgjaFmt2zXI8zbx6aWy4dcfhUmAMwcDysEynYHDD3EZkU+JlZq97+nDk0ftRMHVqn4QCk=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 13
notifications:
  slack:
    rooms:
      - secure: m7EAgRrYaXbo5LDa0Mpi1cQslC0tcxZRc100EjAn+uIPruyABJASIxHUjZeGJQmk98uiS7xk8c+asWx0HgTsj1c8qPMc5rIpfREMGThHBZ3hXzS38DaqehYtwbHPmVSe4tcdt6kj031cHgEzLocMXst9Lj7QO7fKLP/CWT9ZTcL5m8tnIoWMn40r/azvWl0NiFLhZTWdnI9Rn2vyfMuc7EhaUK4gJNwKL8qvSRvdgXR5pq/ETKpXgLTzRwGx7i9fXszecdptx5cRpAGhiRwbqXw9yPYL958KSpRPv+1DE7hX5UbrkecmfYULMfehWtmljTbgfw8cHb1WmIcO1W5M1IEKlBycoX5fxXKUgfv1uG2wF4LYT0U17k6muD/iXDoitq6AgxlDUzVnGQ1n+BQqkdVC9Alsb9fIzzoHejBy7PEXnRbSftnFIBc7AOwmNoQdGaJrNBdSN02OXx3eFuEQpjehdL1l/GMfok9jFlzdK5SpU6k8TPHQBehQ816KFAR+8IEn0XMQsyVVSjMTzYwop/rJONt/Ebtj1ifV+kZb1+IcvAJZ1PTR5ckg4bqFR1Xwg0Ue8pGvlgFtxALf+6FnzrwSpNHBYA/uNFiOG63aI0hNcnbTp0Uan/RI4GdZTzBA37ceQJPozdJ9o1UT9o3HCptnRP0gbSiEC6GvUsWZ0Qg=
    on_success: change
    on_failure: always
